Convert snakemake rehgt pipeline to nextflow 🎉 💛 💚 🖤
Arcadia-Science/2023-rehgt-nextflow pull request #2
Opened 2023-05-05 16:33 UTC by taylorreiter

2023-05-05 17:09 UTC, taylorreiter commented on modules/combine_results.nf
> +    //conda "conda-forge::r-tidyverse=2.0.0 conda-forge::r-janitor=2.2.0"
this was throwing an error i couldn't resolve for some unknown reason. using a yaml fixed it, no idea why.

2023-05-09 23:01 UTC, mertcelebi requested changes
A couple small requests but overall looks great. A couple questions:
* Are you happy with the output directory structure broadly speaking? Or do you need to more process-level customization for it? 
* Overall seems like things should be fine, but do you anticipate any big jobs (in terms of duration)? This would allow us to set our compute environment in a way that we could use on-demand instances for these type of long jobs. Long here would be anything above 6 hours.

2023-05-10 14:51 UTC, taylorreiter commented on bin/blastp_add_taxonomy_info.R
> +#lca_db <- DBI::dbConnect(RSQLite::SQLite(), "inputs/nr_cluster_taxid_formatted_final.sqlite")
ya that's why i keep it in there, it helps me know which files this points to. if it's not too big of an issue i'd love to keep these types of comments inline for now.

2023-05-10 14:52 UTC, taylorreiter commented on bin/combine_results.R
> +# compositional_tsv <- "~/github/2023-rehgt-nextflow/out_full/compositional/Bigelowiella_clusters.tsv"
this was still helpful to me to have this -- if I want to change anything in the script (like even something dumb such as the final order of columns), this helps me dive back in really quickly to the R code and run things inline and play with the intermediate R objects

2023-05-10 15:03 UTC, taylorreiter commented on workflows/rehgt.nf
> +    blastp_against_clustered_nr(ch_BLAST_DB, translate_pangenome.out.aa_rep_seq)
when I was running locally with snakemake with 8 threads, it only took a couple hours. but when i tried to do it containerized within nextflow, even with 6 or 8 threads it would time out after 8 hours.

2023-05-10 15:03 UTC, taylorreiter commented on workflows/rehgt.nf
> +    blastp_add_taxonomy_info(ch_BLAST_TAX, blastp_against_clustered_nr.out.tsv)
my philosophy for keeping separate includes:
1. to make it so that each conda environment was simpler (which could have supported -> docker...but that's already not an option for this pipeline bc some of my rules needed multiple packages). 
2. if the blast process succeeds, but the add tax info step fails, I would be distraught if I lost the BLAST results bc it takes so long to run BLAST.

However, if you think for running on tower it's better to combine this rule with diamond, then I can combine

2023-05-10 15:06 UTC, taylorreiter commented
>  Are you happy with the output directory structure broadly speaking? Or do you need to more process-level customization for it?

i didn't put any energy into naming the output directories. I think it's fine for now but could be improved. Should i put that energy in now?

> Overall seems like things should be fine, but do you anticipate any big jobs (in terms of duration)? This would allow us to set our compute environment in a way that we could use on-demand instances for these type of long jobs. Long here would be anything above 6 hours.

The only "long" one is BLAST. If we can give it enough CPUs, I think 6 hours is plenty (I think between 8 and 16 cpus should be enough to finish within that time frame, but im not totally sure esp since ive only worked with fungi and ticks so far). I've made the process 24 hours by default for the BLAST rule. Do you think we should just set those up as on-demand instances now, or try it and see how it goes?

2023-05-18 17:02 UTC, mertcelebi commented on workflows/rehgt.nf
> +    blastp_add_taxonomy_info(ch_BLAST_TAX, blastp_against_clustered_nr.out.tsv)
I was thinking less in terms of combining them with diamond. It actually is good to keep the diamond process separate for the reason you described. It's more so for some of the subsequent processes (like the 2 TSV manipulation processes immediately following blastp).

2023-05-18 17:02 UTC, mertcelebi approved these changes
Approving!

2023-05-18 17:02 UTC, mertcelebi approved these changes
Approving!

2023-05-18 17:27 UTC, taylorreiter commented on workflows/rehgt.nf
> +    blastp_add_taxonomy_info(ch_BLAST_TAX, blastp_against_clustered_nr.out.tsv)
oh i see. I'm going to leave them separate for now and make an issue to keep thinking about what it makes sense to combine. The TSV lineages added will eventually be fodder to more than one process -- the one that's here now, and then one to predict HGT at a subkingdom level. it might make sense to combine all three eventually. so will document to keep in mind!

2023-05-18 17:27 UTC, merged